inputs:
  source:
    description: “The site handle to screenshot”
    required: true

runs:
  using: "composite"
  steps:
    - id: shoot
      name: Take screenshot
      run: pipenv run python -m newshomepages.shoot single ${{ inputs.source }} -o _dist
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.source }}
        path: _dist
        if-no-files-found: error
