inputs:
  source:
    description: "The site handle to screenshot"
    required: true
  command:
    description: "The tweet.py command to run"
    required: true
  consumer-key:
    required: true
  consumer-secret:
    required: true
  access-token-key:
    required: true
  access-token-secret:
    required: true

runs:
  using: "composite"
  steps:
    - id: tweet
      name: Tweet
      run: pipenv run python newshomepages/tweet.py ${{ inputs.command }} ${{ inputs.source }} -i _dist
      shell: bash
      env:
        TWITTER_CONSUMER_KEY: ${{ inputs.consumer-key }}
        TWITTER_CONSUMER_SECRET: ${{ inputs.consumer-secret }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ inputs.access-token-key }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ inputs.access-token-secret }}
