inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  access-key:
    description: An API key with permission to post to archive.org
    required: true
  secret-key:
    description: An API secret with permission to post to archive.org
    required: true
  collection:
    description: The identifier of the target archive.org collection
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.source }}

    - id: telegram
      name: Telegram
      run: pipenv run python -m newshomepages.archive ${{ inputs.source }}
      shell: bash
      env:
        IA_ACCESS_KEY: ${{ inputs.access-key }}
        IA_SECRET_KEY: ${{ inputs.secret-key }}
        IA_COLLECTION:  ${{ inputs.collection }}