inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  api-key:
    description: An API key with permission to post to Telegram
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.source }}

    - id: telegram
      name: Telegram
      run: pipenv run python -m newshomepages.telegrammer ${{ inputs.source }}
      shell: bash
      env:
        TELEGRAM_API_KEY: ${{ inputs.api-key }}
