inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  telegram-api-key:
    required: true

runs:
  using: "composite"
  steps:
    - id: telegram
      name: Telegram
      run: pipenv run python -m newshomepages.telegrammer ${{ inputs.source }} -i _dist
      shell: bash
      env:
        TELEGRAM_API_KEY: ${{ inputs.telegram-api-key }}
