inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  discord-bot-token:
    description: A bot token with permission to post to Discord
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.source }}

    - id: discord
      name: Discord
      run: pipenv run python -m newshomepages.discorder ${{ inputs.source }}
      shell: bash
      env:
        DISCORD_BOT_TOKEN: ${{ inputs.discord-bot-token }}
