name: Single Screenshot

on:
  workflow_call:
    inputs:
      source:
        description: "The site handle to screenshot"
        required: true
        type: string

jobs:
  take-screenshot:
    name: Take screenshot
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: screenshot
        name: Screenshot
        uses: ./.github/actions/screenshot
        with:
          source: ${{ input.source }}
          twitter-consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitter-consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          twitter-access-token-key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

  telegram:
    name: Post to Telegram
    needs: [take-screenshot]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: telegram
        name: Post to Telegram
        uses: ./.github/actions/telegram
        with:
          source: ${{ input.source }}
          telegram-api-key: ${{ secrets.TELEGRAM_API_KEY }}

  discord:
    name: Post to Discord
    needs: [take-screenshot]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: discord
        name: Post to Discord
        uses: ./.github/actions/discord
        with:
          source: ${{ input.source }}
          discord-bot-token: ${{ secrets.DISCORD_BOT_TOKEN }}
