name: Southern California

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 13,1 * * *'

jobs:
  take-screenshot:
    name: Take screenshot
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        source: ["latimes",]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: screenshot
        name: Screenshot
        uses: ./.github/actions/screenshot
        with:
          source: ${{ matrix.source }}
