name: Southern California

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13,1 * * *"

jobs:
  take-screenshot:
    name: Take screenshot
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        source: ["latimes", "laist", "sdut"]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: screenshot
        name: Screenshot
        uses: ./.github/actions/screenshot
        with:
          source: ${{ matrix.source }}
          twitter-consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitter-consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          twitter-access-token-key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          discord-bot-token: ${{ secrets.DISCORD_BOT_TOKEN }}

      - id: telegram
        name: Post to Telegram
        uses: ./.github/actions/telegram
        with:
          telegram-api-key: ${{ secrets.TELEGRAM_API_KEY }}
