name: U.K. national newspapers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3,9,15,21 * * *"

jobs:
  single-screenshot:
    uses: ./.github/workflows/single-screenshot.yml
    with:
      source: ft-uk
