name: U.S. national television

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0,6,12,18 * * *'

jobs:
  take-screenshot:
    name: Take screenshot
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        source: ["cnn", "foxnews"]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: screenshot
        name: Screenshot
        uses: ./.github/actions/screenshot
        with:
          source: ${{ matrix.source }}
          twitter-consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitter-consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          twitter-access-token-key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
